### ISSUE TITLE
!!! ERROR - error occurred in job (id=node001): remote command 'source /etc/profile && /etc/init.d/portmap start' failed with status 127:

### ISSUE THREAD

**Issue by nishadhka** [brunogrande/starcluster-ami-config#1]
Hi,

Thanks for Packer.io configuration for building a StarCluster AMI. While launching the created AMI, i faced with the error. Based on [this](https://github.com/jtriley/StarCluster/issues/409) I updated the AMI with the commands

```
ln -s /lib/init/upstart-job /etc/init.d/portmap
ln -s /lib/init/upstart-job /etc/init.d/portmap-wait
```

Subsequent starcluster launch with new AMI was not having any issue and worked. May be adding these commands in the Packer.io file solve the issue permenantely.

**Comment by BrunoGrandePhD** [comment]
Hello @nishadhka, 

I'm glad someone has found some use to it! Curiously, I did not run into this issue. Before integrating your suggested changes, which is well appreciated, I'd like to reproduce the error you were running into. 

My first suspicion is that you're not using the same version of StarCluster as I am. I didn't get around to documenting it, but I'm currently using this [pull request](https://github.com/jtriley/StarCluster/pull/549).

**Comment by BrunoGrandePhD** [comment]
I actually integrated this change in 9ad2c84c0ae6fcc4c56eabb4d79f487ad03c28c7. Thanks for the tip!
